### ISSUE TITLE
Port to Sailfish OS?

### ISSUE THREAD

**Issue by Qiangong2** [AsteroidOS/AsteroidOSSync#31]
I think it would be great if you could sync your asteroidOS watch with a sailfish os phone. Two alternatives to android working together.

**Comment by FlorentRevest** [comment]
Hi Qiangong2,

A SailfishOS client has been planned for a while now but always postponed due to lack of time and it being low priority compared to other tasks. This should happen... eventually.

For reference, if anyone is interested in contributing such an app: https://github.com/AsteroidOS/asteroid-btsyncd/issues/1#issuecomment-259124418

**Comment by FlorentRevest** [comment]
Now tracked at https://github.com/AsteroidOS/starfish
