### ISSUE TITLE
Port for Ubuntu touch?

### ISSUE THREAD

**Issue by FloVanGH** [AsteroidOS/AsteroidOSSync#43]
Thanks to the ubports community Ubuntu touch is still alive. Ubuntu touch and asteroid should be a good team.

**Comment by FlorentRevest** [comment]
Take a look at https://github.com/AsteroidOS/asteroid-btsyncd/issues/1
Since then, we also happen to have got https://github.com/AsteroidOS/libasteroid which can help the development of new apps.
If anyone is interested in developing an app, it would certainly be very welcome it but I don't consider this as a high priority task for the near future of Asteroid.

**Comment by FloVanGH** [comment]
Thank you. I hope someone will take care of it or when I find the time I'll have to take a look at it. The code of libasteroid looks great.

**Comment by FlorentRevest** [comment]
Now tracked at https://github.com/AsteroidOS/starfish
