### ISSUE TITLE
Feature Request: Disable phone notifications when watch is connected

### ISSUE THREAD

**Issue by BakaOsaka** [AsteroidOS/AsteroidOSSync#44]
Currently with AsteroidOSSync, if a notification is received, the watch and phone will both vibrate.

Conversely, Wear OS (Former Android Wear) has options to "Silence phone while wearing watch", with toggles to:
- Silence incoming calls
- Silence alerts and notifications

Such options could be added under the existing "Notification settings" menu of AsteroidOSSync, as an alternative to per-app settings for the watch.

_Note:_ This can likely be implemented using the [setRingerMode](https://developer.android.com/reference/android/media/AudioManager.html#setRingerMode(int)) API, with either ```RINGER_MODE_SILENT``` or the depreciated ```VIBRATE_SETTING_OFF``` flags.

**Comment by FlorentRevest** [comment]
Hi @BakaOsaka,
Thank you for the suggestion! It is indeed a very good idea.
However, I am not sure if we should put this in the current "Notification settings" (those are two really different concepts that deserve different pages) or somewhere new.

**Comment by jrtberlin** [comment]
> _Note:_ This can likely be implemented using the [setRingerMode](https://developer.android.com/reference/android/media/AudioManager.html#setRingerMode(int)) API, with either `RINGER_MODE_SILENT` or the depreciated `VIBRATE_SETTING_OFF` flags.

`setRingerMode` behaves strangely on my testing device turning "do not disturb" on with notifications still showing up on the phone as expected without a sound, but not being sent to the watch.  
What confuses me is that my phone runs Android 9.0 and enabling "do not disturb" requires the `ACCESS_NOTIFICATION_POLICY` permission since 7.0. The permission is not declared in the AndroidManifest.xml.

![dnd_asteroid](https://user-images.githubusercontent.com/14153182/54606545-6ee54580-4a4c-11e9-9784-c35cf2a3ac25.png)
