### ISSUE TITLE
Samsung 8+/Oreo - Signal messenger- no notification.

### ISSUE THREAD

**Issue by tengocoffee** [AsteroidOS/AsteroidOSSync#52]
The asteroid OS sync app doesn't seem to see I have signal messenger installed, therefore no notifications are sent.

I'm happy to help test this if you let me know what is required.

Thanks for the app and all the work you have done.

**Comment by FlorentRevest** [comment]
Thanks for reporting @tengocoffee !
I'll also add (as a note for myself) that Riot messenger notifications have also been reported to be missing. Maybe the problem is the same... We'll need to figure it out.
If anyone is willing to debug this issue. It's probably just a matter of putting logs everywhere in https://github.com/AsteroidOS/AsteroidOSSync/blob/master/app/src/main/java/org/asteroidos/sync/utils/NotificationParser.java and then checking in logcat where the notification's content appears and why it is not selected as a notification that can be sent over BLE. Note that it could also be discarded here: https://github.com/AsteroidOS/AsteroidOSSync/blob/master/app/src/main/java/org/asteroidos/sync/services/NLService.java#L144

**Comment by jrtberlin** [comment]
Is this still an issue? I had no problems with Signal since version 1.0.

**Comment by tengocoffee** [comment]
Sorry I no longer have that set-up to test any further. If you have Signal Messenger notifications working with that Samsung model and OS version, please feel free to close this issue.

**Comment by jrtberlin** [comment]
Oreo is outdated anyway. If someone has this issue on pie there is always the option to create a new issue.
