### ISSUE TITLE
Orbot notification spamming watch

### ISSUE THREAD

**Issue by betsythefc** [AsteroidOS/AsteroidOSSync#7]
Hello, I have an LG G Watch (Dory) with bluetooth and the AsteroidOS Sync (installed from F-Droid).

Every second, a notification pops up on the watch with the notification from orbot. Orbot uses a persistent notification that updates with the speed over the tor network. How can I make it so that the watch ignores this notification or stops displaying it on the watch? At present it does not allow for the watch screen to turn off.

**Comment by FlorentRevest** [comment]
Hi betsythefc,

For now there is no way to disable android's persistent notification. If you want a quick and dirty hack you can just blacklist your orbit's package name with a condition here: https://github.com/AsteroidOS/AsteroidOSSync/blob/master/app/src/main/java/org/asteroidos/sync/services/NLService.java#L139 If you want a cleaner and *upstreamable* solution, you can add a dialog to edit a dynamic blacklist here https://github.com/AsteroidOS/AsteroidOSSync/blob/master/app/src/main/java/org/asteroidos/sync/DeviceDetailActivity.java#L153 and use this blacklist in NLService as mentioned above.

An even better fix (or addition) would be to update notifications dynamically on the watch from the events sent by the phone. The phone already sends an "id" value to identify modified notifications and it is extracted by asteroid-btsyncd. However this id is not used to communicate with the DBus "notify" profile on the watch. https://github.com/AsteroidOS/asteroid-btsyncd/blob/master/notificationservice.cpp#L60 Last time I tried to use "id" instead of 0 I got inconsistent results, there may be other changes to add to lipstick or asteroid-launcher but I'm not sure about it.

Good luck,
    Florent

**Comment by TheLastProject** [comment]
See also #1. That pull request never got tested, nor was it a proper fix, but it's about the exact same issue.

**Comment by FlorentRevest** [comment]
This should now be fixed by https://github.com/AsteroidOS/asteroid-btsyncd/commit/5aa3c6e633ad388acd649e17c825ea1e58b33196

**Comment by FlorentRevest** [comment]
Without answer from you I close the issue.
