### ISSUE TITLE
Don't keep location lock

### ISSUE THREAD

**Issue by TheLastProject** [AsteroidOS/AsteroidOSSync#85]
The app seems to constantly ask the OS for the location if set weather location automatically is turned on. This causes significant battery drain. Especially because the weather info itself doesn't update every second, the location checks should probably be about as common as the weather updates.

**Comment by jrtberlin** [comment]
Sorry, for the inconvenience.
The app uses a subscriber model for the location which calls `onLocationChanged()`. I would like to keep the possibility to update the weather info more regular in the future. Since your main issue seems to be "significant battery drain", I set the accuracy to low ( #86 ). This should result in better battery life.

**Comment by jrtberlin** [comment]
We pushed a new release including the improvements.
